### ISSUE TITLE
Use `digestif` instead of `cryptokit`?

### ISSUE THREAD

**Issue by dinosaure** [sporto/jwto#10]
It seems that your software is used by [`dream`](https://github.com/aantron/dream). To be able to use such library with MirageOS, `jwto` should depend on [`digestif`](https://github.com/mirage/digestif) instead of `cryptokit`. `digestif` exists for a long time and it is widely used to compute several hashes (like BLAKE2B or SHA3). The library is a part of the MirageOS project and it is actively maintained.

Would you like to use this library instead of `cryptokit`? I can propose a PR for that.

**Comment by sporto** [comment]
Done
