### ISSUE TITLE
Extracting payload from a decoded token

### ISSUE THREAD

**Issue by xguerin** [sporto/jwto#4]
This is a silly question, but since `t` is not exported in the interface, what is the best way to currently extract the payload of a decoded token ?

**Comment by sporto** [comment]
Not silly at all. I'm not experience with building libs in ocaml. So I might have totally missed exporting something that should. 


Isn't `t` exported here? https://github.com/sporto/jwto/blob/master/lib/jwto.mli#L3

**Comment by xguerin** [comment]
In [the mli](https://github.com/sporto/jwto/blob/master/lib/jwto.mli#L3), `t` is declared but not defined. It is only defined [in the ml](https://github.com/sporto/jwto/blob/f080c7f944896cf13ee0a66be9a218ac77860595/lib/jwto.ml#L66). This boils down to hiding the details of the type `t` and is usually considered good practice to do so in libraries.

All you need is a set of getters to access fields inside your anonymous type, like I did [here](https://github.com/xguerin/jwto/commit/04e23eb28ab6d2fce60019abd790aaef44cda54b) for example. I'll submit that change set as a PR.
