### ISSUE TITLE
Publish 0.3.0 to OPAM

### ISSUE THREAD

**Issue by joseferben** [sporto/jwto#8]
Hey, I really like the API of this package. Unfortunately the latest published version 0.2.1 has no API to get the payload of the token and the type is hidden. 

In version 0.3.0 the getters were added, it would be cool to have that version in OPAM :)

**Comment by sporto** [comment]
I was able to do `opam publish` successfully today (was hitting https://github.com/ocaml-opam/opam-publish/issues/99 before). Should be published soon.

**Comment by joseferben** [comment]
Thanks a lot!
